"""Ad-hoc documentation drift report (Phase 31 Phase 2).

Runs Check Surface D and E in lenient mode against the live repo; writes
a Markdown report to stdout grouped by term. Operators run this for
triage; not wired into the seal flow.

Usage:
    python -m qor.scripts.doc_integrity_drift_report
"""
from __future__ import annotations

import sys
from collections import defaultdict
from pathlib import Path


def _group_findings(findings: list[str], term_regex=None) -> dict[str, list[str]]:
    """Parse 'Term X used/defined in FILE ...' findings into {term: [msgs]}."""
    import re
    pattern = re.compile(r"Term '([^']+)'")
    grouped: dict[str, list[str]] = defaultdict(list)
    for msg in findings:
        m = pattern.search(msg)
        if m:
            grouped[m.group(1)].append(msg)
        else:
            grouped["<unparsed>"].append(msg)
    return dict(grouped)


def _render(grouped_d: dict[str, list[str]], grouped_e: dict[str, list[str]]) -> str:
    lines: list[str] = ["# Documentation Drift Report", ""]
    lines.append(f"Generated by `qor.scripts.doc_integrity_drift_report` in lenient mode.")
    lines.append("")
    lines.append("## Check Surface D (term-drift)")
    lines.append("")
    if not grouped_d:
        lines.append("_No findings._")
    else:
        for term, msgs in sorted(grouped_d.items(), key=lambda kv: (-len(kv[1]), kv[0])):
            lines.append(f"- Term '{term}' ({len(msgs)} findings)")
            for m in msgs[:10]:
                lines.append(f"  - {m}")
            if len(msgs) > 10:
                lines.append(f"  - ... {len(msgs) - 10} more")
    lines.append("")
    lines.append("## Check Surface E (cross-doc conflict)")
    lines.append("")
    if not grouped_e:
        lines.append("_No findings._")
    else:
        for term, msgs in sorted(grouped_e.items(), key=lambda kv: (-len(kv[1]), kv[0])):
            lines.append(f"- Term '{term}' ({len(msgs)} divergent definitions)")
            for m in msgs[:10]:
                lines.append(f"  - {m}")
            if len(msgs) > 10:
                lines.append(f"  - ... {len(msgs) - 10} more")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    import doc_integrity_strict as dis

    glossary = "qor/references/glossary.md"
    repo = "."
    findings_d = dis.check_term_drift(glossary, repo, strict=False)
    findings_e = dis.check_cross_doc_conflicts(glossary, repo, strict=False)
    report = _render(_group_findings(findings_d), _group_findings(findings_e))
    print(report)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
